### ISSUE TITLE
Improved generation of HEAD request

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/augeias#12]
See #9 . Currently, the server fetches the entire object, generates metadata and then throws away the object. Saves some bandwith between the client and Augeias, but can probably be made more efficient between Augeias and the store.

**Comment by BartSaelen** [comment]
Correct meta data is not passed to the client because the use of content_type='application/octet-stream'. The content-length header is not passed in this case.

**Comment by BartSaelen** [comment]
@kmillet can you describe the problem with the HEAD request and content-length header in a separate bug issue. Not sure this is entirely related.

**Comment by kmillet** [comment]
see #15

**Comment by koenedaele** [comment]
@BartSaelen Is the easiest solution making Augeias mime-type aware? So that we can send correct Content Type headers? That way downstream apps don't need to keep mime-types around like they have to do now.

**Comment by BartSaelen** [comment]
Makin Augeias mime-type awara would be nice, but this problem has other roots I think (see #15)

**Comment by claeyswo** [comment]
Solved by #23 no?

**Comment by claeyswo** [comment]
Solved by #23 no?
