### ISSUE TITLE
Mimetype

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/augeias#13]
Currently, Augeias has no idea of the mime-type of the files it's storing. Whenever we serve something to the client, it's served as `Content-Type:application/octet-stream`. So, another application has to track what kind of files it has been storing in Augeias.

Seems like it would be better for Augeias to have some knowledge of that.

**Comment by cahytinne** [comment]
Mimetype can now be served to the client using the function `get_object_info` that must be provided by the stores.
```python 
content_type = collection.object_store.get_object_info(container_key, object_key)['mime']
```
In case of the `PairTreeFileSystemStore`, the  
`magic.from_buffer(open(file_path).read(1048576), mime=True)` cannot guess Microsoft mimetypes. This can be solved by adding configuration to the `/etc/magic` file as described in following link
https://serverfault.com/questions/338087/making-libmagic-file-detect-docx-files/377792#377792
