### ISSUE TITLE
requests.head is not returning correct content-length in nginx environment

### ISSUE THREAD

**Issue by kmillet** [OnroerendErfgoed/augeias#15]
Is it possible to implement a way to get the content-length of a file without first downloading the whole file. Currently we tried to get the content-length by using requests.head but it seems this returns 0 in our setup. (nginx+gunicorn)

**Comment by BartSaelen** [comment]
The problem is this line in the webob response code:
https://github.com/Pylons/webob/blob/master/webob/response.py#L146

**Comment by BartSaelen** [comment]
ok, after setting response.content_length explicitly, this is not an issue

problem is with the service bus handling the request

**Comment by koenedaele** [comment]
Conclusion, not a problem with Augeias. We could implement something like a separat endpoint for metadata, but that's not a priority.
