### ISSUE TITLE
OE specific config

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/augeias#8]
Shouldn't [this](https://github.com/OnroerendErfgoed/augeias/blob/master/augeias/collections/__init__.py#L7) config be removed? This is part of our custom implementation.

**Comment by koenedaele** [comment]
I think they were left there as config for the development environment. But I agree that something more neutral would make more sense.

**Comment by claeyswo** [comment]
Shouldn't [this](https://github.com/OnroerendErfgoed/augeias/blob/master/augeias/__init__.py#L38) setting better default to False? In almost every case an implementation will have to provide it's own custom collections. Having to add an extra setting to prevent from adding the default collections makes less sense than having to add that setting to add the default collections.

**Comment by koenedaele** [comment]
Probably. Think we just need to make sure #6 makes it into 0.2.0 so that it's easier to set up your own implementation. And write some docs on how things work.
